<template>
    <div class="media-wrapper">
        <a
            :href="route('articles.index')"
            class="media-link"
        >
            <SvgVue
                class="media-icon"
                icon="media-news"
            />
        </a>
        <a
            :href="youtube"
            class="media-link"
            target="_blank"
        >
            <SvgVue
                class="media-icon"
                icon="media-youtube"
            />
        </a>
        <a
            :href="facebook"
            class="media-link"
            target="_blank"
        >
            <SvgVue
                class="media-icon"
                icon="media-facebook"
            />
        </a>
        <a
            :href="twitter"
            class="media-link"
            target="_blank"
        >
            <SvgVue
                class="media-icon"
                icon="media-twitter"
            />
        </a>
        <a
            :href="instagram"
            class="media-link"
            target="_blank"
        >
            <SvgVue
                class="media-icon"
                icon="media-instagramm"
            />
        </a>
        <a
            :href="linkedin"
            class="media-link"
            target="_blank"
        >
            <SvgVue
                class="media-icon"
                icon="media-linkedin"
            />
        </a>
    </div>
</template>

<script>
export default {
    data() {
        return {...this.shared('social')}
    }
}
</script>
